### ISSUE TITLE
Enable jsonData in grafana_datasources

### ISSUE THREAD

**Issue by alrosot** [cloudalchemy/ansible-grafana#100]
Hello,

The file [datasources.yml](https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/datasources.yml) is not considering jsonData property (documented at http://docs.grafana.org/administration/provisioning/)

That is not a problem when you are setting up datasources like prometheus. However it becomes a blocker if you ever try to add a cloudwatch datasource like the one below: 

```
apiVersion: 1

datasources:
- name: cloudwatch
  type: cloudwatch
  jsonData:
    authType: arn
    defaultRegion: ap-southeast-2
```

Thank you!
