### ISSUE TITLE
Dashboard title cannot be empty

### ISSUE THREAD

**Issue by albttx** [cloudalchemy/ansible-grafana#108]
It's close to the #77 

I can't import my grafana dashboard

```
- hosts: grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: password42
    grafana_datasources:
      - name: prometheus
        type: prometheus
        url: 'http://localhost:9090'
        access: proxy
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 42
        revision_id: 1
        datasource: prometheus

    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - x.x.x.x:9100
  roles:
    - cloudalchemy.grafana
    - cloudalchemy.prometheus
```

I uncomment the `no_log: true`, here is the output:

```
failed: [x.x.x.x] (item=/tmp/dashboards/42.json) => {"changed": false, "connection": "close", "content": "{\"message\":\"Dashboard title cannot be empty\"}", "content_length": "45", "content_type": "application/json", "date": "Tue, 06 Nov 2018 16:36:48 GMT", "item": "/tmp/dashboards/42.json", "json": {"message": "Dashboard title cannot be empty"}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "status": 400, "url": "http://0.0.0.0:3000/api/dashboards/db"}
```

Any idea ?
