### ISSUE TITLE
Alerting notifications are not updated after created

### ISSUE THREAD

**Issue by boutetnico** [cloudalchemy/ansible-grafana#143]
If you try to update settings of an existing alerting notification channel after it was created this role will not update it.

Steps to reproduce:

1. Create a notification channel
```
grafana_alert_notifications:
  - name: "Send alerts into Slack"
    type: slack
    isDefault: true
    settings:
      url: "REDACTED"
      recipient: "#monitoring"
```

2. Ensure channel is created in Grafana
<img width="439" alt="Screenshot 2019-03-24 at 11 25 23" src="https://user-images.githubusercontent.com/973739/54878074-8f841580-4e27-11e9-9c64-4248b832c4e1.png">

3. Update the settings of the notification channel (Notice addition of `username`)
 ```
grafana_alert_notifications:
  - name: "Send alerts into Slack"
    type: slack
    isDefault: true
    settings:
      url: "REDACTED"
      recipient: "#monitoring"
      username: Grafana
```

4. Check notification settings on Grafana UI.

**Current result**: settings are not updated, username remains blank.

**Expected result**: settings are updated, username = Grafana
