### ISSUE TITLE
Missing database when managing datasources via API?

### ISSUE THREAD

**Issue by bengoa** [cloudalchemy/ansible-grafana#181]
Hello guys,

I'm trying to provision an influxdb datasource using the API method and I'm getting into this error:

```
TASK [./ : Ensure datasources exist (via API)] **********************************************************
failed: [localhost] (item={u'basic_auth_password': u'xx', u'basic_auth_user': u'grafana', u'name': u'telegraf_via_api2', u'database': u'telegraf', u'url': u'http://influxdb.localdomain:8086', u'access': u'proxy', u'user': u'grafana', u'password': u'xx', u'type': u'influxdb'}) => {"ansible_loop_var": "item", "changed": false, "item": {"access": "proxy", "basic_auth_password": "xx", "basic_auth_user": "grafana", "database": "telegraf", "name": "telegraf_via_api2", "password": "xx", "type": "influxdb", "url": "http://influxdb.localdomain:8086", "user": "grafana"}, "msg": "ds_type is influxdb but all of the following are missing: database"}
```
I'm passing the variables like this:

```
    grafana_datasources:
      - name: telegraf_via_api2
        type: influxdb
        access: proxy
        url: http://influxdb.localdomain:8086
        database: telegraf
        user: grafana
        password: "{{ vault_influxdb_grafana_pass }}"
```

I guess we should be passing the `database` parameter to the API as well. 

Using the file provisioning is working perfectly. 

Thanks!
