### ISSUE TITLE
Intended format of dashboards stored in grafana_dashboards_dir

### ISSUE THREAD

**Issue by bwolf** [cloudalchemy/ansible-grafana#229]
**What did you do?**
Setting the variable `grafana_dashboards_dir: 'files/grafana/dashboards'` and putting there a custom dashboard.

**Did you expect to see some different?**
I'm unsure how to associate the datasource with the dashboard. For a dashboard in `grafana_dashboards` we have the ability to specify the datasource. For `grafana_dashboards_dir` we haven't. How to get this going?

**Environment**

* Role version:

    `93f25a8`

* Ansible version information:

    `ansible 2.9.10`

* Variables:

```
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://{{ prometheus_web_listen_address }}'
    basicAuth: false

grafana_dashboards_dir: 'files/grafana/dashboards'

grafana_dashboards:
  - dashboard_id: 11074
    revision_id: 2
    datasource: prometheus
```

* Dashboard
The dashboard in `grafana_dashboards_dir` has an input section:

```
 "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
```

and is referencing the datasource in panels like this `"datasource": "${DS_PROMETHEUS}"`.
