### ISSUE TITLE
potentially invalid yaml syntax in notifiers/ansible.yml

### ISSUE THREAD

**Issue by DO1JLR** [cloudalchemy/ansible-grafana#230]
**What happened?**

The grafana has refused to start. The reason was an invalid yaml syntax in the file /etc/grafana/provisioning/notifiers/ansible.yml

**Did you expect to see some different?**

Of course grafana should not have crashed.

**How to reproduce it (as minimally and precisely as possible)**:

* deploy grafana with the ``grafana_alert_notifications`` as seen below. *(not tested if it will work on a fresh installation)*

**Environment**
+ OS: Debian buster

* Role version:

    `1b00549e7a7a7d71a81082ef3ff5a80e206560c8`

* Ansible version information:

    `ansible --version`
```
ansible 2.9.6
  config file = /home/do1jlr/git/ansible-server/ansible.cfg
  configured module search path = ['/home/do1jlr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/do1jlr/.local/lib/python3.8/site-packages/ansible
  executable location = /home/do1jlr/.local/bin/ansible
  python version = 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
```

* Variables:

```
grafana_alert_notifications:
  - name: "Email Alert"
    type: "email"
    isDefault: true
    settings:
      addresses: "it@example.com"
```

* deployed yaml file:
```
apiVersion: 1
-   isDefault: true
    name: Email Alert
    settings:
        addresses: it@example.com
    type: email
```
* fixed yaml file:
```
---
apiVersion: 1
  - isDefault: true
    name: Email Alert
    settings:
      addresses: it@example.com
    type: email
```

* Ansible playbook execution Logs:

```
TASK [grafana : Enable grafana to ports lower than port 1024] **************************************************************************************************************
ok: [monitoring.wingcon.com]

TASK [grafana : Enable and start Grafana systemd unit] *********************************************************************************************************************
changed: [monitoring.wingcon.com]

TASK [grafana : Check which plugins are installed] *************************************************************************************************************************
skipping: [monitoring.wingcon.com]

TASK [grafana : Install plugins] *******************************************************************************************************************************************

TASK [grafana : Wait for grafana to start (http/s)] ************************************************************************************************************************
fatal: [monitoring.wingcon.com]: FAILED! => changed=false 
  elapsed: 300
  msg: Timeout when waiting for 0.0.0.0:443

```

**Anything else we need to know?**:
