### ISSUE TITLE
--skip-tags grafana_run still starts grafana due to untagged start task

### ISSUE THREAD

**Issue by kunickiaj** [cloudalchemy/ansible-grafana#233]
I was hoping to leverage the grafana_run tag to skip starting Grafana with a placeholder configuration similar to #151. In this case external database whose secrets have not been populated with real values, and I don't wish to attempt to connect to the database as this this playbook is run as part of an image build.

It seems that there's still an explicit start task that will attempt to (and fail) to start Grafana.

https://github.com/cloudalchemy/ansible-grafana/blob/4819fd48c8acbe436174030bb5d49bd098e71194/tasks/configure.yml#L82-L87

Can someone confirm that this task should be tagged with grafana_run? Or is there some other way to achieve completing this playbook with placeholder config values?

**Comment by kunickiaj** [comment]
@bryanspears did you end up running into some issues with this despite adding the `grafana_run` tag?

**Comment by bryanspears** [comment]
@kunickiaj Hey! It's been a little while since I touched on this. I forked a while back and hadn't updated in some time, but it appears that configure restart task doesn't prevent `--skip-tags grafana_run` from doing what you're looking for. I also inject secrets at boot time vs. build (AMI) time.

For reference, but has the same restart stanza in the configure task.
https://github.com/rp-labs/ansible-grafana

**Comment by kunickiaj** [comment]
Ah yeah I was hoping to avoid forking. In an effort to inject secrets at boot I was trying to use placeholder values.

I found that `--skip-tags grafana_run` seemed to work when using the sqlite3 db option however when I have an external database configured, the references "Enable and start Grafana systemd unit" would fail unless the database is actually reachable.

I was under the impression that this gets run because its not one of the tasks that's tagged.

```
  grafana: TASK [cloudalchemy.grafana : Enable and start Grafana systemd unit] ************
    grafana: fatal: [default]: FAILED! => {"changed": false, "msg": "Unable to start service grafana-server: Job for grafana-server.service failed because the control process exited with error code. See \"systemctl status grafana-server.service\" and \"journalctl -xe\" for details.\n"}
    grafana:
    grafana: RUNNING HANDLER [cloudalchemy.grafana : restart grafana] ***********************
```
