### ISSUE TITLE
grafana_provisioning_synced - works or not?

### ISSUE THREAD

**Issue by inkdude** [cloudalchemy/ansible-grafana#241]
**What happened?**
I think it's feature don't work
**Did you expect to see some different?**
I want to my provision settings (dashboard, datasources) is dissapear when i delete from "grafana_dashboards" or "grafana_datasources" in defaults/main.yml
**How to reproduce it (as minimally and precisely as possible)**:
I change grafana_provisioning_synced to true and nothings happens
**Environment**

* Role version:
    `https://github.com/cloudalchemy/ansible-grafana/releases/tag/0.18.0`

* Ansible version information:

    `ansible --version`
    **ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dude/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]**

* Variables:

```
grafana_provisioning_synced
```

* Ansible playbook execution Logs:

```
-
```

**Anything else we need to know?**:

For example
I add some datasources with provision

```
# Datasources to configure
grafana_datasources:
 - name: "Prometheus"
   type: "prometheus"
   access: "proxy"
   url: "http://prometheus.XXX:19090"
   basicAuth: true
   basicAuthUser: "XXX"
   basicAuthPassword: "XXX"
   isDefault: true
   jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true

 - name: "ClickHouse"
   type: "ClickHouse"
   access: "proxy"
   url: "http://XXX:8123"
   basicAuth: false
   isDefault: false
   jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true

```

How can i remove one of this (if i already deploy both of this datasources? Just comment in main.yml? Or what?

grafana_provisioning_synced - is this for that?
