### ISSUE TITLE
Import grafana dashboards skipping with variable dashboard_id

### ISSUE THREAD

**Issue by patsevanton** [cloudalchemy/ansible-grafana#289]
**What happened?**

Import grafana dashboards skipping with variable dashboard_id

**Did you expect to see some different?**
Import grafana dashboards not skipping with variable dashboard_id

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Role version:

    `- cloudalchemy.grafana, 0.18.0`

* Ansible version information:

    `ansible [core 2.12.2]`

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
---
- name: Install prometheus and Grafana
  hosts: prometheus
  roles:
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: enter_your_secure_password
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false
        dashboards:
        - dashboard_id: 1860
          revision_id: 26
          datasource: prometheus
```

**Anything else we need to know?**:
