### ISSUE TITLE
Failed to download grafana dashboard from grafana.net 

### ISSUE THREAD

**Issue by JornDM** [cloudalchemy/ansible-grafana#304]
TASK [cloudalchemy.grafana : download grafana dashboard from grafana.net to local directory] ***
FAILED - RETRYING: [monitor -> localhost]: download grafana dashboard from grafana.net to local directory (5 retries left).
FAILED - RETRYING: [monitor -> localhost]: download grafana dashboard from grafana.net to local directory (4 retries left).
FAILED - RETRYING: [monitor -> localhost]: download grafana dashboard from grafana.net to local directory (3 retries left).FAILED - RETRYING: [monitor -> localhost]: download grafana dashboard from grafana.net to local directory (2 retries left).FAILED - RETRYING: [monitor -> localhost]: download grafana dashboard from grafana.net to local directory (1 retries left).
failed: [monitor -> localhost] (item={'dashboard_id': '7362', 'revision_id': '5', 'datasource': 'prometheus'}) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": {"dashboard_id": "7362", "datasource": "prometheus", "revision_id": "5"}, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
monitor                    : ok=21   changed=1    unreachable=0    failed=1    skipped=26   rescued=0    ignored=0

I get this error when I was trying to provision my monitor server with some dashboards. 
These are the vars that I configured for Grafana using this role:

```
# -----------------------
#       Grafana
# -----------------------

# Creates a Grafana Administrator user 'Admin' for installation Grafana
grafana_security:
  admin_user: admin 
  admin_password: admin 

# Configure Grafana datasource
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://192.168.10.5:9090'
    basicAuth: false

grafana_dashboards:
    # Dashboard voor SQL
  - dashboard_id: '7362'
    revision_id: '5'
    datasource: 'prometheus'
```

I am using this on an Ubuntu server 22.04 (vagrant box: bento/ubuntu-22.04)

Kind regards
