### ISSUE TITLE
Datasources provisionning

### ISSUE THREAD

**Issue by phineas0fog** [cloudalchemy/ansible-grafana#63]
Hello, your roles are very cool but I can't configure it for datsources creation... I don't touch the sample values : 
```yaml
# Datasources to configure
grafana_datasources: []
 - name: "Prometheus"
   type: "prometheus"
   access: "proxy"
   url: "http://prometheus.mydomain"
   basicAuth: true
   basicAuthUser: "admin"
   basicAuthPassword: "password"
   isDefault: true
   jsonData: '{"tlsAuth":false,"tlsAuthWithCACert":false,"tlsSkipVerify":true}'
```

And got this error : 
```
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/home/.../Ansible/monitoring/roles/grafana/defaults/main.yml': line 153, column 2, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

grafana_datasources: []
 - name: "Prometheus"
 ^ here

```

I don't understand what I fail... Thanks to you and sorry if it's a stupid question

**Comment by paulfantom** [comment]
You have syntax error. Since you define empty list with `grafana_datasources: []` but later you try to add elements to this list.

So instead of
```
grafana_datasources: []
 - name: "Prometheus"
   type: "prometheus"
   access: "proxy"
   url: "http://prometheus.mydomain"
   basicAuth: true
   basicAuthUser: "admin"
   basicAuthPassword: "password"
   isDefault: true
   jsonData: '{"tlsAuth":false,"tlsAuthWithCACert":false,"tlsSkipVerify":true}'
```
you should have:
```
# Datasources to configure
grafana_datasources:
 - name: "Prometheus"
   type: "prometheus"
   access: "proxy"
   url: "http://prometheus.mydomain"
   basicAuth: true
   basicAuthUser: "admin"
   basicAuthPassword: "password"
   isDefault: true
   jsonData: '{"tlsAuth":false,"tlsAuthWithCACert":false,"tlsSkipVerify":true}'
```

Notice `[]` brackets after `grafana_datasource:`

**Comment by phineas0fog** [comment]
Oh, yes thanks you, but now, I do this : 
```yaml
grafana_datasources:
  # - name: "comeon"
  #   type: "influxdb"
  #   access: "direct"
  #   url: "http://{{ influx_host }}:8086"
  #   database: 'lizard00'
  #   basicAuth: false
  #   url_username: "{{ influx_user }}"
  #   url_password: "{{ influx_pass }}"
  #   isDefault: true
  #   jsonData: '{"tlsAuth":false,"tlsAuthWithCACert":false,"tlsSkipVerify":true}'
  - name: "datasource-influxdb"
    grafana_url: "http://{{ grafana_host }}:3000"
    grafana_user: "{{ grafana_admin_uname }}"
    grafana_password: "{{ grafana_admin_pass }}"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://{{ influx_host }}:8086"
    database: "telegraf"
    time_interval: ">10s"
```

And there is an error that I don't understand: I get an 401 error with "Invalid username or password" but I know that my creds are good because I can use them to log in the web interface...
