### ISSUE TITLE
Pass variables through playbook

### ISSUE THREAD

**Issue by kagarlickij** [cloudalchemy/ansible-grafana#88]
Hi there, I've created playbook which tries to pass some mandatory vars: 

```
- hosts: all
  become: true
  vars:
    grafana_security.admin_password: adm_pwd
  roles:
    - role: cloudalchemy.grafana
```

..but it doesn't work:
```
ERROR! Invalid variable name in vars specified for Play: 'grafana_security.admin_password' is not a valid variable name
```

Please advice how to do it correctly?

**Comment by paulfantom** [comment]
You need to specify full `grafana_security` dictionary. Ansible doesn't allow changing only parts of dicts defined in `defaults/main.yml`

So in your case you need to specify:
```yaml
- hosts: all
  become: true
  vars:
    grafana_security:
      admin_password: adm_pwd
      admin_user: adm
  roles:
    - role: cloudalchemy.grafana
```
