### ISSUE TITLE
Config for Elasticsearch datasource

### ISSUE THREAD

**Issue by kagarlickij** [cloudalchemy/ansible-grafana#89]
Please advice how to configure `grafana_datasources` for Elasticsearch, 
I have to add URL and index, no auth is required, example of config in UI: [http://prntscr.com/kkxb4q](url)

**Comment by paulfantom** [comment]
We are following standards set by grafana project. So this: http://docs.grafana.org/features/datasources/elasticsearch/#configure-the-datasource-with-provisioning should easily translate to this: https://github.com/cloudalchemy/ansible-grafana/blob/69d16c5634056481498057f798b8d05f565e70ef/defaults/main.yml#L197-L206

**Comment by kagarlickij** [comment]
To manage this config I set datasource manually and get config from WEB API:
`curl -H "Authorization: Bearer eyJ...X0=" http://34.xx.yy.19:3000/api/datasources/name/elasticsearch`, it looked like:
```
{
  "id": 1,
  "orgId": 1,
  "name": "kag-el1",
  "type": "elasticsearch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "https://vpc-kag-el1-sgshjf7eq7mhhyllggkdgynhpu.us-east-1.es.amazonaws.com",
  "password": "",
  "user": "",
  "database": "metricbeat-*",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": true,
  "jsonData": {
    "esVersion": 56,
    "keepCookies": [],
    "maxConcurrentShardRequests": 256,
    "timeField": "@timestamp"
  },
  "secureJsonFields": {},
  "version": 3,
  "readOnly": true
}
```

Based on it and link @paulfantom provided above I've set config to use with Ansible:
```
    grafana_datasources:
    - name: elasticsearch
      type: elasticsearch
      access: proxy
      url: "https://vpc-kag-el1-sgshjf7eq7mhhyllggkdgynhpu.us-east-1.es.amazonaws.com"
      basicAuth: false
      database: "metricbeat-*"
      isDefault: true
      jsonData:
        esVersion: 56
        maxConcurrentShardRequests: 256
        timeField: "@timestamp"
```

Hope it will help somebody)
